@startuml
package executablegames{
 class Util{
 +getramdomnumber()
 +roldiceNumber()
 }
    class Main{

    }

    Class MainGames{
        -Games[] games
        -ListOfPlayers listOfPlayers
        -ListOfResults listOfResults
        -CRUD crud
        -Statistics statistics
        +MainGames()
        +printMenu()
        +printGamesOption()
        +executeOption()
    }

    class CRUD{

    }

    class Statistics{

    }


    package players{
        class ListOfPlayers{
        }

        class ListOfResults{
        }
    }

    package games{
        class Game{
            -int NUMBEROFPLAYERS
            -TypeGame typeGame
            +{abstract}introduction()
            +{abstract}execute()
            +{abstract}resume()
            +{abstract}getNumberOfPlayers()
        }
    }

    Main *-- MainGames

    MainGames *-- CRUD
    MainGames *-- Statistics
    MainGames *-- ListOfPlayers
    MainGames *--"2" Game
    MainGames *-- ListOfResults
    MainGames ..>Util

@enduml